### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [evgeny-khirin/klisp#1]
looks cool, is this a new Lisp compiler? your project description is still empty: "No description, website, or topics provided."

keep it up, cheers!

**Comment by evgeny-khirin** [comment]
Thanks. Yes, it is new compiler. The K-Lisp similar to Common Lisp, but not same. Main design goal was to get tight integration with C without foreign function interface. So that code in C may call Lisp functions easy and vice versa. Specs are in docs/specs.txt.

It is my hobby project and it does not have web site etc.

Regards,
Evgeny.
